#!/usr/bin/env sh

{
    thisfile="$0"
    thisdir="$(dirname $0)"
    . "$thisdir/common"

    deps_exec() {
        dep=$1
        depscript="$thisdir/deps.d/$dep"
        shift
        $depscript exec "$@" || return $?
    }

    deps_install_dep() {
        dep=$1
        depscript="$thisdir/deps.d/$dep"
        if [ ! -f $depscript ] || [ ! -x $depscript ]; then
            logerr "cannot install $dep: $depscript not found or not executable"
            exit 1
        fi

        if ! $depscript check; then
            log "installing $dep"
            for subdep in $($depscript deps); do
                log " => $dep depends on $subdep"
                unset dep
                unset depscript
                all_install_dep $subdep
                dep=$1
                depscript="$thisdir/deps.d/$dep"
            done
            $depscript install
            if ! $depscript check; then
                logerr "failed to install $dep"
                exit 1
            fi
        fi
    }

    deps_install() {
        for depscript in $(find ${thisdir}/deps.d -maxdepth 1 -type f); do
            if [ -x $depscript ]; then
                dep=$(basename $depscript)
                deps_install_dep $dep
            fi
        done
    }

    command=$1
    shift
    case $command in
        exec | install)
            deps_$command "$@"
            ;;
        *)
            logexit "command not supported: $command"
            ;;
    esac
}
