#!/usr/bin/env sh

{
    thisdir="$(dirname $0)"
    . "$thisdir/common"

    PSOCRATIC_DIR="$HOME/.psocratic"

    install_dep() {
        dep=$1
        depscript="$thisdir/deps/$dep"
        if [ ! -f $depscript ] || [ ! -x $depscript ]; then
            logerr "cannot install $dep: $depscript not found or not executable"
            exit 1
        fi

        log "checking for $dep"
        if ! $depscript check; then
            log "checking dependencies of $dep"
            for subdep in $($depscript deps); do
                log " => $dep depends on $subdep"
                unset dep
                unset depscript
                install_dep $subdep
                dep=$1
                depscript="$thisdir/deps/$dep"
            done
            $depscript install
            if ! $depscript check; then
                logerr "failed to install $dep"
                exit 1
            fi
        fi
    }

    install_deps() {
        for depscript in $(find $thisdir/deps -maxdepth 1 -type f); do
            if [ -x $depscript ]; then
                dep=$(basename $depscript)
                install_dep $dep
            fi
        done
    }

    copyargs="$@"
    psocratic_dir="$PSOCRATIC_DIR"
    while [ $# -gt 0 ]; do
        arg=$1
        case $arg in
            -psocratic-dir)
                psocratic_dir=$2
                shift
                ;;
        esac
        shift
    done

    install_deps

    "$thisdir/aws/google-sso" $copyargs
    if [ 0 -ne $? ]; then
        logexit "failed to log into Psocratic Google account"
    fi

    github_auth=$("$thisdir/github/auth" $copyargs)
    if [ 0 -ne $? ]; then
        logexit "failed to log into GitHub"
    fi
    github_token=$(echo "$github_auth" | $thisdir/deps/jq exec -r .token)
    if [ 0 -ne $? ]; then
        logexit "failed to parse token from\n$github_auth"
    fi

    "$thisdir/github/clone" \
        -github-token $github_token \
        -github-repo psocratic/psocratic \
        -local-dest $psocratic_dir
    if [ 0 -ne $? ]; then
        logexit "failed to clone git@github.com/psocratic/psocratic to $psocratic_dir"
    fi
}
