#!/usr/bin/env sh

{
    DEFAULT_PSOCRATIC_DIR="$HOME/.psocratic"
    DEFAULT_PSOCRATIC_REPO="psocratic/psocratic"

    thisdir="$(dirname $0)"
    . "$thisdir/common"
    deps="$thisdir/deps"

    aws_google_sso() {
        "$thisdir/aws/google-sso" "$@"; return $?
    }

    detect_psocratic_dir() {
        [ -e "$1" ] && return 0 || return 1
    }

    detect_psocratic_dir_env() {
        if [ -n "$PSOCRATIC_DIR" ]; then
            echo "$PSOCRATIC_DIR"
            return 0
        else
            logerr "no PSOCRATIC_DIR environment variable detected"
            return 1
        fi
    }

    detect_psocratic_dir_export() {
        shell_rc_file="$1"
        source="$HOME/.*shrc $HOME/.*profile $shell_rc_file"
        results=$($deps exec grep -nsP '^(?!\s*#\s*)[^#]*export\s+PSOCRATIC_DIR' $source)

        if [ -n "$results" ]; then
            echo "$results"
            return 0
        else
            logerr "no PSOCRATIC_DIR export detected"
            return 1
        fi
    }

    github_auth() {
        "$thisdir/github/auth" "$@"; return $?
    }

    github_clone() {
        "$thisdir/github/clone" \
            -github-token $1 \
            -github-repo $2 \
            -local-dest $3; return $?
    }

    install_deps() {
        "$(dirname $0)/deps" install; return $?
    }

    shell_append_psocratic_init_to_rc_file() {
        psocratic_dir="$1"
        shell_rc_file="$2"

        rcstring="\n[ -d $psocratic_dir ] && export PSOCRATIC_DIR=\"$psocratic_dir\" && export PATH=\"$psocratic_dir/toolbelt:\$PATH\""

        if [ -z "$shell_rc_file" ] \
            && ! shell_rc_file=$(shell_get_rc_file); then
            logerr "could not determine shell rc file"
            logerr "please add the following to your shell's initialization file:"
            >&2 echo "$rcstring"
            return 1
        fi

        uname="$(uname -s)"
        if [ "$uname" != "Darwin" ]; then
            echo "$rcstring" >> "$shell_rc_file"
        else
            echo "$rcstring" >> "$HOME/.profile"
            if ! $($deps exec grep -sqP \
                    "^\s*.\s*($HOME/|\$HOME|~/).profile" "$shell_rc_file"); then
                echo "\n. \$HOME/.profile" >> "$shell_rc_file"
            fi
        fi
    }

    shell_get_rc_file() {
        shell=$(basename $SHELL)

        case $shell in
            bash) rcfile="$HOME/.bashrc" ;;
            zsh) rcfile="$HOME/.zshrc" ;;
            *) return 1 ;;
        esac

        echo $rcfile
    }

    copyargs="$@"
    psocratic_dir="$DEFAULT_PSOCRATIC_DIR"
    shell_rc_file=""
    while [ $# -gt 0 ]; do
        arg=$1
        case $arg in
            -psocratic-dir) psocratic_dir=$2 shift ;;
            -shell-rc-file) shell_rc_file=$2 shift ;;
        esac
        shift
    done

    install_deps \
        || logexit "failed to install all deps"

    detect_psocratic_dir $psocratic_dir \
        && logexit "-psocratic-dir already exists at $psocratic_dir; \
            please remove or move to another location before proceeding"
    psocratic_dir_env=$(detect_psocratic_dir_env) \
        && logexit "detected environment variable PSOCRATIC_DIR=$psocratic_dir_env; \
            please unset before proceeding"
    psocratic_dir_export=$(detect_psocratic_dir_export $shell_rc_file) \
        && logerr "detected shell rc scripts that export PSOCRATIC_DIR:" \
        && echo $psocratic_dir_export | while read line; do echo "\t$line"; done \
        && logexit "please remove or comment out before proceeding"

    aws_google_auth=$(aws_google_sso "$copyargs") \
        || logexit "failed to log into Psocratic Google account"
    github_auth=$(github_auth "$copyargs") \
        || logexit "failed to log into GitHub"
    github_token=$(echo "$github_auth" | $deps exec jq -r .token) \
        || logexit "failed to parse token from\n$github_auth"
    github_clone $github_token "$DEFAULT_PSOCRATIC_REPO" "$psocratic_dir" \
        || logexit "failed to clone $DEFAULT_PSOCRATIC_REPO to $psocratic_dir"
    shell_append_psocratic_init_to_rc_file $psocratic_dir $shell_rc_file

    psocratic_email=$(echo $aws_google_auth \
        | $deps exec jq -r .user_email)
    aws_access_key=$(echo $aws_google_auth \
        | $deps exec jq -r .aws_access_key_id)
    aws_secret_key=$(echo $aws_google_auth \
        | $deps exec jq -r .aws_secret_access_key)
    aws_session_token=$(echo $aws_google_auth \
        | $deps exec jq -r .aws_session_token)
    aws_security_token=$(echo $aws_google_auth \
        | $deps exec jq -r .aws_security_token)

    export PSOCRATIC_DIR="$psocratic_dir"
    export PATH="$psocratic_dir/toolbelt:$PATH" \
    psocratic deps install                            \
        && psocratic user identify                    \
            -aws-access-key "$aws_access_key"         \
            -aws-secret-key  "$aws_secret_key"        \
            -aws-session-token "$aws_session_token"   \
            -aws-security-token "$aws_security_token" \
            -email "$psocratic_email"                 \
            -github-token "$github_token"             \
        || return $?
}
