#!/usr/bin/env sh

{
    . "$(dirname $0)/../../common"

    java_standard_check() {
        which java > /dev/null || return 1
    }

    java_standard_deps() {
        echo "pkgmgr"
    }

    java_standard_exec() {
        javapath=$(java_standard_path)
        $javapath "$@"
    }

    java_standard_install() {
        pkgmgr="$(dirname $0)/../pkgmgr"
        $pkgmgr install openjdk-8-jdk-headless
        return $?
    }

    java_standard_path() {
        java_standard_check && which java
    }

    command=$1
    shift
    case $command in
        check | deps | exec | install | path)
            java_standard_$command "$@"
            ;;
    esac
}
