#!/usr/bin/env sh

{   . "$(dirname $0)/../common"
    deps="$(dirname $0)/../deps"

    aws_google_auth_check() {
        PATH="$PATH:$HOME/.local/bin:$(python -m site --user-base)/bin:$PATH" which aws-google-auth > /dev/null || return 1
    }

    aws_google_auth_deps() {
        echo "python pip"
    }

    aws_google_auth_exec() {
        aws_google_authpath=$(aws_google_auth_path)
        $aws_google_authpath "$@"
        return $?
    }

    aws_google_auth_install() {
        $deps exec pip install --upgrade --user aws-google-auth
    }

    aws_google_auth_path() {
        PATH="$PATH:$HOME/.local/bin:$(python -m site --user-base)/bin:$PATH" which aws-google-auth
    }

    command=$1
    shift
    case $command in
        check | deps | exec | install | path)
            aws_google_auth_$command $@
            ;;
    esac
}
