#!/usr/bin/env sh

{   . "$(dirname $0)/../common"
    deps="$(dirname $0)/../deps"

    awscli_check() {
        if PATH="$PATH:$HOME/.local/bin:$(python -m site --user-base)/bin" which aws > /dev/null; then
            return 0
        fi
        return 1
    }

    awscli_deps() {
        echo "python pip"
    }

    awscli_exec() {
        awsclipath=$(awscli_path)
        $awsclipath $@
        return $?
    }

    awscli_install() {
        $deps exec pip install --upgrade --user awscli
    }

    awscli_path() {
        PATH="$PATH:$HOME/.local/bin:$(python -m site --user-base)/bin" which aws
    }

    command=$1
    shift
    case $command in
        check | deps | exec | install | path)
            awscli_$command $@
            ;;
    esac
}
