#!/usr/bin/env sh

{
    . "$(dirname $0)/../common"

    grep_check() {
        PATH="$HOME/.local/bin:$PATH"
        which grep > /dev/null || return 1
        echo teststring | grep -qP teststring 2>/dev/null || return 1
    }

    grep_exec() {
        greppath=$(grep_path)
        $greppath "$@"
    }

    grep_deps() {
        echo ""
    }

    grep_install() {
        uname=$(uname -a)
        if [ "$uname" = "Darwin" ]; then
            pkgmgr="$(dirname $0)/pkgmgr"
            "$pkgmgr" install grep
        else
            logerr "will not automatically install grep"
            return 1
        fi
    }

    grep_path() {
        grep_check && PATH="$HOME/.local/bin:$PATH" which grep
    }

    command=$1
    shift
    case $command in
        check | deps | exec | install | path)
            grep_$command "$@"
            ;;
        *)
            logexit "grep does not support command: $command"
    esac
}
