#!/usr/bin/env sh

{   . "$(dirname $0)/../common"
    deps="$(dirname $0)/../deps"

    head_check() {
        which head > /dev/null || return 1
    }

    head_exec() {
        headpath=$(head_path)
        $headpath "$@"
    }

    head_deps() {
        echo ""
    }

    head_install() {
        >&2 echo "head will not be installed automatically"
        exit 1
    }

    head_path() {
        head_check && which head
    }

    command=$1
    shift
    case $command in
        check | deps | exec | install | path)
            head_$command "$@"
            ;;
    esac
}
