#!/usr/bin/env sh

{
    case "$(uname -s)" in
        Darwin*)
            impl="mac"
            ;;
        *)
            impl="standard"
            ;;
    esac

    command=$1
    pkg_impl="${0}.d/java-$impl"
    shift
    case $command in
        check | deps | install | name | selfinstall)
            $pkg_impl $command "$@"
            ;;
        exec)
            $pkg_impl install "$@"
            ;;
        *)
            logexit "unrecognized java command: $command"
            ;;
    esac
}
