#!/usr/bin/env sh

{
    . "$(dirname $0)/../common"

    jq_check() {
        PATH="$HOME/.local/bin:$PATH"
        which jq > /dev/null || return 1
    }

    jq_deps() {
        echo "pkgmgr"
    }

    jq_exec() {
        jqpath=$(jq_path)
        $jqpath "$@"
    }

    jq_install() {
        pkgmgr="$(dirname $0)/pkgmgr"
        $pkgmgr install jq
        return $?
    }

    jq_path() {
        PATH="$HOME/.local/bin:$PATH"
        jq_check && which jq
    }

    command=$1
    shift
    case $command in
        check | deps | exec | install | path)
            jq_$command "$@"
            ;;
    esac
}
