#!/usr/bin/env sh

{   . "$(dirname $0)/../common"
    deps="$(dirname $0)/../deps"

    pip_check() {
        PATH="$HOME/.local/bin:$PATH" 
        which pip > /dev/null && return 0
        which pip3 > /dev/null && return 0
        return 1
    }

    pip_deps() {
        echo "python curl"
    }

    pip_exec() {
        PATH="$HOME/.local/bin:$PATH" 
        pippath=$(pip_path)
        $pippath $@
    }

    pip_install() {
        if ! $deps exec curl https://bootstrap.pypa.io/get-pip.py > /tmp/get-pip.py; then
            >&2 echo failed to download pip installer
            return 1
        fi
        if ! $deps exec python /tmp/get-pip.py --user; then
            >&2 echo failed to install pip
        fi
    }

    pip_path() {
        PATH="$HOME/.local/bin:$PATH" 
        for pip in pip pip3; do
            if which $pip > /dev/null; then
                which $pip
                return
            fi
        done
        return 1
    }

    command=$1
    shift
    case $command in
        check | deps | exec | install | path)
            pip_$command $@
            ;;
    esac
}
