#!/usr/bin/env sh

{
    . "$(dirname $0)/../../../common"
    deps="$(dirname $0)/../../../deps"

    dmg_check() {
        which diskutil  > /dev/null || return 1
        which hdiutil   > /dev/null || return 1
        which installer > /dev/null || return 1
    }

    dmg_deps() {
        echo "sudo"
    }

    dmg_install() {
        dmg="" dmg_set=0
        pkg="" pkg_set=0
        vol="" vol_set=0

        while [ $# -gt 0 ]; do
            arg="$1"
            case $arg in
                -dmg)
                    dmg="$2" dmg_set=1 shift ;;
                -pkg)
                    pkg="$2" pkg_set=1 shift ;;
                -vol)
                    vol="$2" vol_set=1 shift ;;
            esac
            shift
        done

        [ $dmg_set -eq 1 ] || return 1
        [ $pkg_set -eq 1 ] || return 1
        [ $vol_set -eq 1 ] || return 1

        hdiutil attach "$dmg" || return 1

        $deps exec sudo installer -pkg "$pkg" -target / || return 1
        diskutil unmount "$vol"; return $?
    }

    dmg_name() {
        echo "dmg"
    }

    dmg_path() {
        dmg_check
        echo $0
    }

    dmg_selfinstall() {
        logexit "dmg will not be automatically installed"
    }

    command=$1
    shift 1
    case $command in
        check | deps | install | name | path | selfinstall)
            dmg_$command "$@"
            ;;
        *)
            logexit "unsupported command for dmg pkgmgr $command"
            ;;
    esac
}
