#!/usr/bin/env sh

{
    . "$(dirname $0)/../../common"
    deps="$(dirname $0)/../../deps"

    apt_check() {
        which apt-get > /dev/null
    }

    apt_deps() {
        echo ""
    }

    apt_install() {
        $deps exec sudo apt-get install \
            -y --no-install-suggests \
            --no-install-recommends "$@"
    }

    apt_name() {
        echo "apt-get"
    }

    apt_path() {
        apt_check && which apt-get
    }

    apt_selfinstall() {
        logexit "apt will not be automatically installed"
    }

    command=$1
    shift 1
    case $command in
        check | deps | install | name | path | selfinstall)
            apt_$command "$@"
            ;;
        *)
            logexit "unsupported command for apt pkgmgr $command"
            ;;
    esac
}
